spring:
  profiles:
    group:
      local: common
      dev: common

  data.redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

pennyway:
  server:
    domain:
      local: ${PENNYWAY_DOMAIN_LOCAL:127.0.0.1:8080}
      dev: ${PENNYWAY_DOMAIN_DEV:127.0.0.1:8080}

oauth2:
  client:
    provider:
      kakao:
        jwks-uri: ${KAKAO_JWKS_URI:https://kauth.kakao.com}
        secret: ${KAKAO_CLIENT_SECRET:liuhil5068l2j5o0912}
      google:
        jwks-uri: ${GOOGLE_JWKS_URI:https://www.googleapis.com}
        secret: ${GOOGLE_CLIENT_SECRET:123456789012-67hm9vokrt6ukmiwtvd8ak67oflecm.apps.googleusercontent.com}
      apple:
        jwks-uri: ${APPLE_JWKS_URI:https://appleid.apple.com}
        secret: ${APPLE_CLIENT_SECRET:pennyway-jayang-was}

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev