spring:
  profiles:
    group:
      local: common
      dev: common

  data.redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

app:
  question-address: ${ADMIN_ADDRESS}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

pennyway:
  server:
    domain:
      local: ${PENNYWAY_DOMAIN_LOCAL}
      dev: ${PENNYWAY_DOMAIN_DEV}

oauth2:
  client:
    provider:
      kakao:
        jwks-uri: ${KAKAO_JWKS_URI}
        secret: ${KAKAO_CLIENT_SECRET}
      google:
        jwks-uri: ${GOOGLE_JWKS_URI}
        secret: ${GOOGLE_CLIENT_SECRET}
      apple:
        jwks-uri: ${APPLE_JWKS_URI}
        secret: ${APPLE_CLIENT_SECRET}

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev