spring:
  profiles:
    group:
      local: common
      dev: common

  data.redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

  cloud:
    aws:
      sns:
        credentials:
          access-key: ${AWS_SNS_ACCESS_KEY:access-key}
          secret-key: ${AWS_SNS_SECRET_KEY:secret-key}
        region:
          static: ${AWS_SNS_REGION:republic-of-korea-1}
      s3:
        credentials:
          access-key: ${AWS_S3_ACCESS_KEY:access-key}
          secret-key: ${AWS_S3_SECRET_KEY:secret-key}
        region:
          static: ${AWS_S3_REGION:ap-northeast-2}
        bucket:
          name: ${AWS_S3_BUCKET_NAME:pennyway}
      cloudfront:
        domain: ${AWS_CLOUDFRONT_DOMAIN:https://cdn.cloudfront.net}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}

app:
  question-address: ${ADMIN_ADDRESS:team.collabu@gmail.com}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:pennyway}
    password: ${MAIL_PASSWORD:password}
  firebase:
    config:
      file: ${FIREBASE_CONFIG_FILE:firebase-adminsdk.json}
    project:
      id: ${FIREBASE_PROJECT_ID:pennyway-12345}

pennyway:
  server:
    domain:
      local: ${PENNYWAY_DOMAIN_LOCAL:127.0.0.1:8080}
      dev: ${PENNYWAY_DOMAIN_DEV:127.0.0.1:8080}

  rabbitmq:
    chat:
      queue: ${RABBITMQ_CHAT_QUEUE:chat.queue}
      exchange: ${RABBITMQ_CHAT_EXCHANGE:chat.exchange}
      routing: ${RABBITMQ_CHAT_ROUTING:chat.room.*}

oauth2:
  client:
    provider:
      kakao:
        jwks-uri: ${KAKAO_JWKS_URI:http://localhost}
        secret: ${KAKAO_CLIENT_SECRET:liuhil5068l2j5o0912}
      google:
        jwks-uri: ${GOOGLE_JWKS_URI:http://localhost}
        secret: ${GOOGLE_CLIENT_SECRET:123456789012-67hm9vokrt6ukmiwtvd8ak67oflecm.apps.googleusercontent.com}
        issuer: ${GOOGLE_ISSUER:https://google.com}
      apple:
        jwks-uri: ${APPLE_JWKS_URI:http://localhost}
        secret: ${APPLE_CLIENT_SECRET:pennyway-jayang-was}

distributed-coordination:
  chat-server:
    url: ${CHAT_SERVER_URL:ws://localhost:8000/chat}

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test