spring:
  profiles:
    group:
      local: common
      dev: common

pennyway:
  domain:
    local: ${PENNYWAY_DOMAIN_LOCAL}
    dev: ${PENNYWAY_DOMAIN_DEV}

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev