spring:
  profiles:
    group:
      local: common
      prod: common

  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data.redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    database: MySQL
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
    com.zaxxer.hikari.HikariConfig: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    database: MySQL
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect