spring:
  profiles:
    group:
      local: common, domain-service, domain-rdb, domain-redis, infra
      dev: common, domain-service, domain-rdb, domain-redis, infra

server:
  port: ${SOCKET_SERVER_PORT:8081}

pennyway:
  socket:
    chat:
      endpoint: ${SOCKET_CHAT_ENDPOINT:/ws}
      allowed-origin-patterns: ${ALLOWED_ORIGIN_PATTERNS:*}
  rabbitmq:
    validate-connection: true
    chat-join-event-listener: true

message-broker:
  external:
    host: ${MESSAGE_BROKER_HOST:localhost}
    port: ${MESSAGE_BROKER_PORT:5672}
    system-id: ${MESSAGE_BROKER_SYSTEM_ID:guest}
    system-password: ${MESSAGE_BROKER_SYSTEM_PASSWORD:guest}
    client-id: ${MESSAGE_BROKER_CLIENT_ID:guest}
    client-password: ${MESSAGE_BROKER_CLIENT_PASSWORD:guest}
    user-prefix: ${MESSAGE_BROKER_USER_PREFIX:/usr}
    publish-exchange: ${MESSAGE_BROKER_PUBLISH_EXCHANGE:/topic}
    heartbeat-send-interval: ${MESSAGE_BROKER_HEARTBEAT_SEND_INTERVAL:20000}
    heartbeat-receive-interval: ${MESSAGE_BROKER_HEARTBEAT_RECEIVE_INTERVAL:20000}

jwt:
  secret-key:
    access-token: ${JWT_ACCESS_SECRET_KEY:exampleSecretKeyForPennywaySystemAccessSecretKeyTestForPadding}

---
spring:
  config:
    activate:
      on-profile: local

log:
  config:
    filename: socket-local

---
spring:
  config:
    activate:
      on-profile: dev

log:
  config:
    filename: socket-dev
    maxHistory: 3
    maxFileSize: 10MB
    totalSizeCap: 500MB

---
spring:
  config:
    activate:
      on-profile: test