spring:
  profiles:
    group:
      local: common, domain, infra
      dev: common, domain, infra

  batch:
    job:
      enabled: false

  task:
    scheduling:
      pool:
        size: 5
      shutdown:
        await-termination: true # 애플리케이션 종료 시 모든 Task가 종료될 때까지 대기
        await-termination-period: 60000 # 대기 시간 60초

  datasource:
    hikari:
      maximum-pool-size: 2

  data:
    redis:
      repositories:
        enabled: false

  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfigurationV2

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test