package kr.co.pennyway.common.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * 에러 발생 이유 코드
 */
@Getter
@RequiredArgsConstructor
public enum ReasonCode {
    ZERO(0),

    /* 400_BAD_REQUEST */
    INVALID_REQUEST_SYNTAX(1),
    MISSING_REQUIRED_PARAMETER(2),
    MALFORMED_PARAMETER(3),
    MALFORMED_REQUEST_BODY(4),

    /* 401_UNAUTHORIZED */
    MISSING_OR_INVALID_AUTHENTICATION_CREDENTIALS(1),
    EXPIRED_OR_REVOKED_TOKEN(2),
    INSUFFICIENT_PERMISSIONS(3),
    TAMPERED_OR_MALFORMED_TOKEN(4),

    /* 403_FORBIDDEN */
    ACCESS_TO_THE_REQUESTED_RESOURCE_IS_FORBIDDEN(1),
    IP_ADDRESS_BLOCKED(2),
    USER_ACCOUNT_SUSPENDED_OR_BANNED(3),
    ACCESS_TO_RESOURCE_NOT_ALLOWED_FOR_USER_ROLE(4),

    /* 404_NOT_FOUND */
    REQUESTED_RESOURCE_NOT_FOUND(1),
    INVALID_URL_OR_ENDPOINT(2),
    RESOURCE_DELETED_OR_MOVED(3),

    /* 405_METHOD_NOT_ALLOWED */
    REQUEST_METHOD_NOT_SUPPORTED(1),
    ATTEMPTED_TO_ACCESS_UNSUPPORTED_METHOD(2),

    /* 406_NOT_ACCEPTABLE */
    REQUESTED_RESPONSE_FORMAT_NOT_SUPPORTED(1),

    /* 409_CONFLICT */
    REQUEST_CONFLICTS_WITH_CURRENT_STATE_OF_RESOURCE(1),
    RESOURCE_ALREADY_EXISTS(2),
    CONCURRENT_MODIFICATION_CONFLICT(3),

    /* 412_PRECONDITION_FAILED */
    PRECONDITION_REQUEST_HEADER_NOT_MATCHED(1),
    IF_MATCH_HEADER_OR_IF_NONE_MATCH_HEADER_NOT_MATCHED(2),

    /* 422_UNPROCESSABLE_CONTENT */
    REQUIRED_PARAMETERS_MISSING_IN_REQUEST_BODY(1),
    VALIDATION_ERROR_IN_REQUEST_BODY(2),
    ;

    private final int code;

    @Override
    public String toString() {
        return name();
    }
}
