jwt:
  secret-key:
    access-token: ${JWT_ACCESS_SECRET_KEY}
    refresh-token: ${JWT_REFRESH_SECRET_KEY}
  expiration-time:
    # milliseconds 단위
    access-token: ${JWT_ACCESS_EXPIRATION_TIME} # 30m (30 * 60 * 1000)
    refresh-token: ${JWT_REFRESH_EXPIRATION_TIME} # 7d (7 * 24 * 60 * 60 * 1000)

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: prod