spring:
  profiles:
    group:
      local: common, domain-service, domain-rdb, domain-redis, infra
      dev: common, domain-service, domain-rdb, domain-redis, infra

jwt:
  secret-key:
    access-token: ${JWT_ACCESS_SECRET_KEY:exampleSecretKeyForPennywaySystemAccessSecretKeyTestForPadding}
    refresh-token: ${JWT_REFRESH_SECRET_KEY:exampleSecretKeyForPennywaySystemRefreshSecretKeyTestForPadding}
  expiration-time:
    # milliseconds 단위
    access-token: ${JWT_ACCESS_EXPIRATION_TIME:1800000} # 30m (30 * 60 * 1000)
    refresh-token: ${JWT_REFRESH_EXPIRATION_TIME:604800000} # 7d (7 * 24 * 60 * 60 * 1000)

pennyway:
  rabbitmq:
    validate-connection: true

---
spring:
  config:
    activate:
      on-profile: local

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

log:
  config:
    path: ./logs
    filename: app-local

---
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true

log:
  config:
    filename: app-dev
    maxHistory: 7
    maxFileSize: 10MB
    totalSizeCap: 500MB

---
spring:
  config:
    activate:
      on-profile: test

pennyway:
  rabbitmq:
    validate-connection: false